# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build ANTLR Recognizer

on:
  [ push, pull_request ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install antlr4-tools
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build ANTLR
      run: |
        antlr4 -o tmp/formal-lang-course/gen -listener -visitor -Dlanguage=Python3 Gram.g4
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: antlr-gen
        path: tmp/formal-lang-course/gen
